---

apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: default
  labels:
    k8s-app: telegraf
data:
  telegraf.conf: |+
    [global_tags]
      env = "$ENV"
    [agent]
      interval = "60s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "10s"
      flush_interval = "30s"
      flush_jitter = "10s"
      debug = true
      quiet = false
      #logfile = "/var/log/telegraf/telegraf.log"
      hostname = "$HOSTNAME"
      omit_hostname = false
    #[[outputs.file]]
      #files = ["stdout"]
      #data_format = "influx"
    [[outputs.influxdb]]
      urls = ["$MONITOR_HOST"]
      database = "$MONITOR_DATABASE"
      retention_policy = "$MONITOR_RETENTION_POLICY"
      write_consistency = "any"
      timeout = "15s"
      username = "$MONITOR_USERNAME"
      password = "$MONITOR_PASSWORD"
     [[inputs.postgresql]]
      address = "host=localhost port=5432 user=postgres password=password dbname=postgres sslmode=disable"
      databases = ["test1", "postgres"]
