apiVersion: v1
kind: Service
metadata:
  name: goweb1-1-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: goweb1-1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30036
