apiVersion: v1
kind: Pod
metadata:
  name: goweb1-2
  namespace: default
  labels:
    app: goweb1-2
spec:
  containers:
    - name: goweb1
      image: coderdba/goweb1:latest
      ports:
      - containerPort: 8081
      volumeMounts:
      - name: secret-volume
        mountPath: /tmp/messages
  volumes:
    - name: secret-volume
      secret:
        secretName: goweb1defaultmessage
        items:
        - key: message_text
          path: message1.txt
  restartPolicy: Never
