# https://kubernetes.io/docs/reference/access-authn-authz/rbac/

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: sa1-cr-read-secrets
rules:
  - apiGroups: 
    - core # for pods
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
