- name: Docker pull image etcd
  docker_image:
    name: k8s.gcr.io/etcd:3.4.13-0
    source: pull

- name: Docker pull image kube-apiserver
  docker_image:
    name: k8s.gcr.io/kube-apiserver:v1.21.2
    source: pull

- name: Docker pull image kube-scheduler
  docker_image:
    name: k8s.gcr.io/kube-scheduler:v1.21.2
    source: pull

- name: Docker pull image kube-controller-manager
  docker_image:
    name: k8s.gcr.io/kube-controller-manager:v1.21.2
    source: pull

- name: Docker pull image kube-proxy
  docker_image:
    name: k8s.gcr.io/kube-proxy:v1.21.2
    source: pull

- name: Docker pull image calico node
  docker_image:
    name: calico/node:v3.19.1
    source: pull

- name: Docker pull image calico pod2daemon-flexvol
  docker_image:
    name: calico/pod2daemon-flexvol:v3.19.1
    source: pull

- name: Docker pull image calico cni
  docker_image:
    name: calico/cni:v3.19.1
    source: pull

- name: Docker pull image calico kube-controllers
  docker_image:
    name: calico/kube-controllers:v3.19.1
    source: pull

- name: Docker pull image coredns
  docker_image:
    name: k8s.gcr.io/coredns/coredns:v1.8.0
    source: pull

- name: Docker pull image pause
  docker_image:
    name: k8s.gcr.io/pause-amd64:3.1
    source: pull

#docker pull gcr.io/google_containers/kube-apiserver-amd64:v1.21.2
#docker pull gcr.io/google_containers/kube-scheduler-amd64:v1.21.2 
#docker pull gcr.io/google_containers/kube-controller-manager-amd64:v1.21.2 
#docker pull gcr.io/google_containers/kube-proxy-amd64:v1.21.2
#docker pull quay.io/calico/node:v3.19.1 (https://hub.docker.com/r/calico/node/tags)
#docker pull quay.io/calico/pod2daemon-flexvol:v3.19.1
#docker pull quay.io/calico/cni:v3.19.1
#docker pull quay.io/calico/kube-controllers:v3.19.1
#docker pull k8s.gcr.io/coredns/coredns:v1.8.0
#docker pull gcr.io/google-containers/pause-amd64:3.2
