apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ca-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: http-svc
          servicePort: 80
  tls:
  - secretName: tls-secret
