apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:admin-user
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:admin-user
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: admin
