- name: Model Node Setup
  hosts: all
  roles:
  - { role: node-prep }

- name: Pull Docker Images
  hosts: all
  roles:
  - { role: docker-pull }

- name: Install Kubernetes tools
  hosts: all
  roles:
  - { role: kube-tools-install }

