apiVersion: v1
kind: Pod
metadata:
  name: goweb1-1
  namespace: default
  labels:
    app: goweb1-1
spec:
  containers:
    - name: goweb1
      image: coderdba/goweb1:latest
      ports:
      - containerPort: 8081
      volumeMounts:
      - name: config-volume
        mountPath: /tmp/messages
  volumes:
    - name: config-volume
      configMap:
        name: goweb1defaultmessage
        items:
        - key: message_text
          path: message1.txt
  restartPolicy: Never
